// frontend/src/components/vannessa/Upload.jsx
import React, { useState } from 'react';
import './Upload.css';

const Upload = () => {
  const [documents, setDocuments] = useState([
    {
      name: 'ID Document / Passport',
      fileName: '',
      file: null,
      status: 'Pending'
    },
    {
      name: 'Proof of Address',
      fileName: '',
      file: null,
      status: 'Pending'
    },
    {
      name: 'Bank Statement',
      fileName: '',
      file: null,
      status: 'Pending'
    }
  ]);

  const onFileChange = (event, index) => {
    const file = event.target.files[0];
    if (file) {
      const updatedDocuments = [...documents];
      updatedDocuments[index] = {
        ...updatedDocuments[index],
        fileName: file.name,
        file: file,
        status: 'Ready for upload'
      };
      setDocuments(updatedDocuments);
    }
  };

  const removeFile = (index) => {
    const updatedDocuments = [...documents];
    updatedDocuments[index] = {
      ...updatedDocuments[index],
      fileName: '',
      file: null,
      status: 'Pending'
    };
    setDocuments(updatedDocuments);
  };

  const isFormValid = () => {
    return documents.some(doc => doc.file !== null);
  };

  const onSubmit = async (event) => {
    event.preventDefault();
    
    if (!isFormValid()) {
      alert('Please select at least one file to upload.');
      return;
    }

    try {
      // TODO: Implement actual file upload logic
      console.log('Documents to upload:', documents.filter(doc => doc.file));
      
      // Simulate upload process
      const updatedDocuments = documents.map(doc => ({
        ...doc,
        status: doc.file ? 'Uploaded successfully' : doc.status
      }));
      
      setDocuments(updatedDocuments);
      alert('Documents uploaded successfully!');
    } catch (error) {
      console.error('Upload failed:', error);
      alert('Upload failed. Please try again.');
    }
  };

  return (
    <div className="upload-container">
      <h2>Document Verification</h2>
      <p>
        Please upload the required documents to verify your identity and start using
        stokvel services.
      </p>

      <form onSubmit={onSubmit}>
        {documents.map((document, index) => (
          <div className="form-group" key={index}>
            <div className="document-section">
              <div className="document-title">
                <i className="fas fa-info-circle"></i>
                <label>{document.name}</label>
              </div>
              <div className="upload-section">
                <input
                  type="file"
                  onChange={(e) => onFileChange(e, index)}
                  id={`file${index}`}
                  accept=".pdf,.jpg,.jpeg,.png"
                />
                <span>{document.fileName || "No file chosen"}</span>
                {document.fileName && (
                  <button
                    type="button"
                    onClick={() => removeFile(index)}
                  >
                    Remove
                  </button>
                )}
              </div>
              <span className="status">{document.status}</span>
            </div>
          </div>
        ))}

        <button 
          type="submit" 
          disabled={!isFormValid()} 
          className="btn btn-primary"
        >
          Submit for Verification
        </button>
      </form>
    </div>
  );
};

export default Upload;

// Vanessa-Angular/Angular/Angular/Stokvels/src/app/pages/upload/upload.component.ts
import { Component } from '@angular/core';
import { UploadService } from '../../core/services/upload.service';
import { CommonModule } from '@angular/common'; // Import CommonModule for ngFor and ngIf

@Component({
  selector: 'app-upload',
  standalone: true, // This makes it a standalone component
  imports: [CommonModule], // Import CommonModule here
  templateUrl: './upload.component.html',
  styleUrls: ['./upload.component.css']
})
export class UploadComponent {
  documents = [
    { name: 'ID Document', fileName: '', file: null, status: 'Not Uploaded' },
    { name: 'Proof of Address', fileName: '', file: null, status: 'Not Uploaded' },
    { name: 'Bank Statement', fileName: '', file: null, status: 'Not Uploaded' }
  ];

  userId: number = 1; // Example userId; modify as needed

  constructor(private uploadService: UploadService) {}

  onFileChange(event: any, index: number): void {
    const file = event.target.files[0];
    if (file) {
      this.documents[index].file = file;
      this.documents[index].fileName = file.name;
      this.documents[index].status = 'Uploaded';
    }
  }

  removeFile(index: number): void {
    this.documents[index].file = null;
    this.documents[index].fileName = '';
    this.documents[index].status = 'Not Uploaded';
  }

  isFormValid(): boolean {
    return this.documents.every(doc => doc.file !== null);
  }

  onSubmit(): void {
    if (this.isFormValid()) {
      this.documents.forEach(doc => {
        if (doc.file) {
          this.uploadService.uploadDocument(this.userId, doc.file, doc.name).subscribe(
            response => {
              console.log(`${doc.name} uploaded successfully`, response);
              alert('Documents uploaded successfully!');
            },
            error => {
              console.error(`Error uploading ${doc.name}`, error);
              alert(`Failed to upload ${doc.name}!`);
            }
          );
        }
      });
    } else {
      alert('Please upload all required documents.');
    }
  }
}

<div class="upload-container">
  <h2>Document Verification</h2>
  <p>
    Please upload the required documents to verify your identity and start using
    stokvel services.
  </p>

  <form (ngSubmit)="onSubmit()">
    <div class="form-group" *ngFor="let document of documents; let i = index">
      <div class="document-section">
        <div class="document-title">
          <i class="fas fa-info-circle"></i>
          <label>{{ document.name }}</label>
        </div>
        <div class="upload-section">
          <input
            type="file"
            (change)="onFileChange($event, i)"
            [attr.id]="'file' + i"
          />
          <span>{{ document.fileName || "No file chosen" }}</span>
          <button
            type="button"
            (click)="removeFile(i)"
            *ngIf="document.fileName"
          >
            Remove
          </button>
        </div>
        <span class="status">{{ document.status }}</span>
      </div>
    </div>

    <button type="submit" [disabled]="!isFormValid()" class="btn btn-primary">
      Submit for Verification
    </button>
  </form>
</div>
