// frontend/src/components/vannessa/Home.jsx
import React from 'react';
import { useNavigate } from 'react-router-dom';
import './Home.css';

const Home = () => {
  const navigate = useNavigate();

  const goRegister = () => {
    navigate('/register');
  };

  const goLogin = () => {
    navigate('/login');
  };

  return (
    <div className="home">
      <div className="hero">
        <h1 className="title">Welcome to Stokvel</h1>
        <p className="subtitle">Simple community savings. Create an account or sign in.</p>

        <div className="actions">
          <button className="btn primary" onClick={goRegister}>
            Register
          </button>
          <button className="btn ghost" onClick={goLogin}>
            Login
          </button>
        </div>
      </div>
    </div>
  );
};

export default Home;

// Vannessa/home/home.component.ts
import { Component } from '@angular/core';
import { Router, RouterLink } from '@angular/router';

@Component({
  selector: 'app-home',
  standalone: true,
  imports: [RouterLink],
  templateUrl: './home.component.html',
  styleUrls: ['./home.component.css']
})
export class HomeComponent {
  constructor(private router: Router) {}
  goRegister() { this.router.navigateByUrl('/register'); }
  goLogin() { this.router.navigateByUrl('/login'); }
  
}

<div class="home">
  <div class="hero">
    <h1 class="title">Welcome to Stockvel</h1>
    <p class="subtitle">Simple community savings. Create an account or sign in.</p>

    <div class="actions">
      <button class="btn primary" (click)="goRegister()">Register</button>
      <button class="btn ghost" (click)="goLogin()">Login</button>
      
    </div>
  </div>
</div>
